# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harrison Liddiard
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://harrisonliddiard.com" # the base hostname & protocol for your site
description: "Harrison Liddiard is a software engineer at PayPal and a UCLA graduate, previously at The New York Times and hackNY. See his projects and resume." # 150-160 chars max
twitter_username: HLiddiard
github_username:  liddiard
linkedin_username: liddiard
collections:
  projects:
    output: true
    permalink: /project/:path/
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# Build settings
markdown: kramdown
